"""empty message

Revision ID: 920e6a7ea04f
Revises: 9671de4c4be1
Create Date: 2022-08-10 04:53:28.330140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '920e6a7ea04f'
down_revision = '9671de4c4be1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('id', sa.Integer(), nullable=True))
    op.alter_column('Show', 'venue_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Show', 'artist_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Show', 'artist_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Show', 'venue_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('Show', 'id')
    # ### end Alembic commands ###
